FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
RUN mkdir -p /home/app
WORKDIR /home/app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -r alpine-x64 --self-contained true /p:PublishTrimmed=true -o ./publish


FROM alpine:3.9.4

RUN apk add --no-cache libstdc++ libintl icu

EXPOSE 80
EXPOSE 443

RUN mkdir -p /home/app
WORKDIR /home/app
COPY --from=build /home/app/publish/ /home/app/
RUN ls
ENTRYPOINT ["./vb-boletos-netcore", "--urls", "http://0.0.0.0:80"]