### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY . .
RUN npm run build:development
### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf 
COPY --from=build /usr/src/app/dist/ng-ventaboletos /usr/share/nginx/html